### ISSUE TITLE
msitools issue seems to be resolved

### ISSUE THREAD

**Issue by dvtomas** [est31/msvc-wine-rust#1]
The readme says that *"Once there is support by msitools for the msi files involved, the requirement on the second toolchain will be replaced by a requirement on msitools."*

According to https://bugzilla.gnome.org/show_bug.cgi?id=789020 it seems that the issue has been resolved, perhaps it's good time to do what the README says? I'm afraid I don't have the knowledge to do it myself..

**Comment by est31** [comment]
The bug itself is fixed but there hasn't been a release since... it will take a while until we get one I guess https://github.com/GNOME/msitools/commits/master

**Comment by est31** [comment]
Nice, there's been a new release since: https://github.com/GNOME/msitools/releases/tag/v0.98

Note to myself: update the README.
