### ISSUE TITLE
How to compile crates using the cc crate?

### ISSUE THREAD

**Issue by dvc94ch** [est31/msvc-wine-rust#6]
I'm trying to write some windows networking code using this method, but the `wepoll-sys` crate fails to compile as it has a little bit of c code in it. Is it possible to cross compile c code to windows too or only pure rust crates?

**Comment by est31** [comment]
In theory yes, but then you'll likely need more parts of the SDK. I recommend downloading the enterprise WDK as linked to in the readme which contains more relevant files.
