### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libcmt.lib'

### ISSUE THREAD

**Issue by ntrischi** [est31/msvc-wine-rust#7]
For some reason link.exe cannot resolve `libcmt.lib`. I'm attempt to statically compile a binary with MSVC on Linux Ubuntu. I'm using the following rustflags: `rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=/DEBUG:NONE"]` 

The linker will use the statically linked CRT libraries: `libcmt.lib,` `libvcruntime.lib`, and `libucrt.lib`.

Any help is appreciated.

**Comment by est31** [comment]
Does #5 fix it for you?

**Comment by ntrischi** [comment]
Thank you. That fixed the issue.
